# Generated by Django 4.2.13 on 2024-06-14 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mascotas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('edad', models.IntegerField()),
                ('sexo', models.CharField(choices=[['Macho', 'Macho'], ['Hembra', 'Hembra']], max_length=50)),
                ('vacuna', models.CharField(choices=[['SI', 'SI'], ['NO', 'NO']], max_length=50)),
                ('desparacitado', models.CharField(choices=[['SI', 'SI'], ['NO', 'NO']], max_length=50)),
                ('estado', models.CharField(choices=[['Adoptado', 'Adoptado'], ['En adopcion', 'En adopcion']], max_length=100)),
                ('castrado', models.CharField(choices=[['SI', 'SI'], ['NO', 'NO']], max_length=50)),
                ('caracteristicas', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Mascota',
                'verbose_name_plural': 'Mascotas',
            },
        ),
    ]
