# Generated by Django 4.2.13 on 2024-09-12 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0002_mascotas_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascotas',
            name='imagen1',
            field=models.ImageField(blank=True, null=True, upload_to='mascotas/'),
        ),
        migrations.AddField(
            model_name='mascotas',
            name='imagen2',
            field=models.ImageField(blank=True, null=True, upload_to='mascotas/'),
        ),
        migrations.AlterField(
            model_name='mascotas',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='mascotas/'),
        ),
    ]
