# Generated by Django 4.2.13 on 2024-09-12 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0005_alter_mascotas_imagen1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascotas',
            name='imagen1',
            field=models.ImageField(blank=True, null=True, upload_to='mascotas/'),
        ),
    ]
